name: Bug Report
description: Report a bug or unexpected behavior in Craft Agents
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below so we can reproduce and fix the issue.

  - type: input
    id: version
    attributes:
      label: Craft Agents Version
      description: "Found in Settings or the title bar (e.g. 0.4.6)"
      placeholder: "0.4.6"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows 11
        - Windows 10
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Other)
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: "e.g. macOS 15.3, Windows 11 24H2, Ubuntu 24.04"
      placeholder: "macOS 15.3"
    validations:
      required: true

  - type: dropdown
    id: ai_provider
    attributes:
      label: AI Provider
      description: Which AI provider/connection are you using?
      options:
        - Anthropic API (direct)
        - Anthropic API (custom endpoint)
        - OpenAI / Codex
        - Copilot (GitHub)
        - Other
    validations:
      required: true

  - type: input
    id: model
    attributes:
      label: Model
      description: "Which model are you using? (e.g. Claude Opus 4.6, GPT-4.1)"
      placeholder: "Claude Opus 4.6"

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Screen Recordings
      description: |
        For **UI issues**, please attach screenshots or screen recordings showing the problem.
        You can drag and drop images/videos directly into this field.

  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: |
        For **non-UI issues** (crashes, errors, connection problems), please attach relevant logs from a debug session.

        Launch the app with `-- --debug` and reproduce the issue. See the [Troubleshooting section in the README](https://github.com/lukilabs/craft-agents-oss#troubleshooting) for platform-specific commands and log file locations.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem (MCP sources used, workspace config, etc.)
